kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: jornada-k8s-ebpf
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"