apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "regra1"
spec:
  description: "Política L7 para restringir acessos a determinadas chamadas HTTP"
  endpointSelector:
    matchLabels:
      org: imperio
      class: estrela-da-morte
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: imperio
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "POST"
          path: "/v1/request-landing"
